# Generated by Django 3.2.5 on 2021-11-29 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicatie2', '0002_pontaj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pontaj',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
    ]
