# Generated by Django 3.2.9 on 2021-12-12 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicatie2', '0005_userextend'),
        ('aplicatie2', '0007_userextend'),
    ]

    operations = [
    ]
