# Generated by Django 3.2.9 on 2021-12-12 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicatie2', '0008_merge_0005_userextend_0007_userextend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companies',
            name='company_type',
            field=models.CharField(choices=[('SRL', 'S.R.L.'), ('SA', 'S.A.')], max_length=5),
        ),
    ]
